name: test graphile-config

on: [push]

jobs:
  runtest:
    name: Run test
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,graphile-config}"
      package: "graphile-config"
      testcommand: "test"
      args: "--ci"
    