name: test tamedevil

on: [push]

jobs:
  runtest:
    name: Run test
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil}"
      package: "tamedevil"
      testcommand: "test"
      args: "--ci"
    