name: Linting

on: [push, pull_request]

jobs:
  ESLint:
    name: ESLint
    runs-on: ubuntu-latest

    env:
      CI: true # Should already be set to TRUE by Github?
      TERM: xterm
      FORCE_COLOR: 1
      NODE_VERSION: 22.x # Should be moved to a repo envvar
      NODE_OPTIONS: "--max-old-space-size=4096" # Give eslint more space?

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - run: yarn --immutable

      - name: "Build"
        run: yarn build

      - name: "Prepack"
        run: yarn workspaces foreach --parallel --topological --all run prepack

      - name: "Lint Code"
        run: yarn eslint .

  Prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - run: yarn --immutable

      - name: "Check Code Format"
        run: yarn prettier:check

  depcheck:
    name: Benjie's depcheck script
    runs-on: ubuntu-latest

    env:
      TERM: xterm
      FORCE_COLOR: 1
      NODE_VERSION: 22.x # Should be moved to a repo envvar

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - run: yarn --immutable

      - name: "Build Code"
        run: yarn build && yarn prepack:all

      - name: "Run depcheck script"
        run: node scripts/benjies-depcheck.mjs

  doccheck:
    name: Documentation checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - run: yarn --immutable

      - name: "Ensure SQL is lowercase"
        run: node scripts/ensure-sql-is-lowercase.mjs

      - name: "Ensure links don't end in /"
        run: node scripts/ensure-no-slashes-on-internal-links.mjs
