name: Posttest

on: [push, pull_request]

jobs:
  star_and_build_websites:
    name: star/build website posttests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "{@localrepo/star-website,@localrepo/graphile-build-website}"
      testcommand: "posttest"
  grafast_and_postgraphile_websites:
    name: Grafast/PostGraphile website posttests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "{@localrepo/grafast-website,@localrepo/postgraphile-website}"
      testcommand: "posttest"
  small_packages:
    name: Small package posttests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "{@dataplan/pg,pg-sql2,tamedevil}"
      testcommand: "posttest"
