name: Test postgraphile v4

on: [push]

jobs:
  runtest:
    name: Run test
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,postgraphile}"
      package: "postgraphile"
      testcommand: "test:v4"
      args: "--ci"