name: Test

on: [push, pull_request]

jobs:
  dataplan_pg:
    name: "@dataplan/pg tests"
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,@dataplan/pg}"
      package: "@dataplan/pg"
      testcommand: "test"
      args: "--ci"

  postgraphile:
    name: PostGraphile tests
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,postgraphile}"
      package: "postgraphile"
      testcommand: "test"
      args: "--ci"

  small_packages:
    name: Small package tests
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,@grafserv/persisted,@graphile/lru,@graphile/simplify-inflection,@localrepo/grafast-bench,@localrepo/grafast-website,grafast,graphile,graphile-config,graphile-utils,jest-serializer-graphql-schema,pg-introspection,grafserv}"
      package: "{pg-sql2,tamedevil,@grafserv/persisted,@graphile/lru,@graphile/simplify-inflection,@localrepo/grafast-bench,@localrepo/grafast-website,grafast,graphile,graphile-config,graphile-utils,jest-serializer-graphql-schema,pg-introspection,grafserv}"
      testcommand: "test"
      args: "--ci"
