name: Test postgraphile schema

on: [push, pr]

jobs:
  runtest:
    name: Run test
    uses: ./.github/workflows/test-base.yml
    with:
      prepackPackages: "{pg-sql2,tamedevil,postgraphile}"
      package: "postgraphile"
      testcommand: "test:schema"
      args: "--ci"
